
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarPolice.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Car
{

    public Car()
    {

        this.results = new HashSet<results>();

    }


    public int id { get; set; }

        [Display(Name = "Номер кузова")]
        public string body_no { get; set; }
        [Display(Name = "Госномер")]
        public string license_plate { get; set; }
        [Display(Name = "Марка")]
        public string mark { get; set; }
        [Display(Name = "Цвет")]
        public string color { get; set; }
        [Display(Name = "Номер двигателя")]
        public string engine_no { get; set; }
        [Display(Name = "Номер тех паспорта")]
        public int pass_no { get; set; }



    public virtual ICollection<results> results { get; set; }

}

}
