
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarPolice.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CarOwner
{

    public CarOwner()
    {

        this.results = new HashSet<results>();

    }

        
        public int id { get; set; }
        [Display(Name = "ФИО владельца")]
        public string full_name { get; set; }
        [Display(Name = "Адрес")]
        public string address { get; set; }
        [Display(Name = "Пол")]
        public string gender { get; set; }
        [Display(Name = "Номер водительского удостоверения")]
        public int driver_license_no { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Дата рождения")]
        public System.DateTime DOB { get; set; }



    public virtual ICollection<results> results { get; set; }

}

}
